baseURL = "https://zenith-john.github.io/"
languageCode = "zh-cn"
title = "忘言阁 Zenith John's Nonsense"
theme = "hugo-theme-cleanwhite"
hasCJKLanguage = true
preserveTaxonomyNames = true
paginate = 10

[params]
    header_image = "img/header.webp"
    sidebar_avatar = "img/avatar.webp"
    sidebar_about_description = "Graduate Student in Mathematics, Emacser, Linuxer"
    about_me = true
    desription = "张南涛，数学研究生，Emacser, 开源爱好者 | 实迷途其未远，觉今是而昨非"
    showtoc = false
    featured_tags = true

    image_404 = "img/header.webp"
    title_404 = "方可方不可，方不可方可"

    [params.social]
    email = "zenith-john@foxmail.com"
    github = "https://github.com/zenith-john/"

    [[params.additional_menus]]
    title = "数学 Math"
    href = "top/math/"
    [[params.additional_menus]]
    title = "妄言 Nonsense"
    href = "top/nonsense/"
    [[params.additional_menus]]
    title = "归档 Archives"
    href = "top/archives/"


[markup]
    [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true
markup = "md"
math = "true"

[taxonomies]
tag = 'tags'
series = 'series'
