baseURL = "https://zenith-john.github.io/"
languageCode = "zh-cn"
title = "Zenith John's Nonsense"
theme = "hugo-theme-cleanwhite"
hasCJKLanguage = true
preserveTaxonomyNames = true
paginate = 10

[params]
    header_image = "img/header.png"
    sidebar_avatar = "img/avatar.jpeg"
    sidebar_about_description = "Emacser, Graduate Student in Mathematics"
    about_me = true
    showtoc = false

    [params.social]
    email = "zenith-john@foxmail.com"
    github = "https://github.com/zenith-john/"


[markup]
    [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true
markup = "md"
math = "true"

[taxonomies]
category = 'categories'
tag = 'tags'
