baseURL = "https://zenith-john.github.io/"
languageCode = "zh-cn"
title = "Zenith John's Nonsense"
theme = "hugo-theme-cleanwhite"
hasCJKLanguage = true
preserveTaxonomyNames = true
paginate = 10

[params]
    header_image = "img/header.png"
    sidebar_avatar = "img/avatar.jpeg"
    sidebar_about_description = "Emacser, Graduate Student in Mathematics"
    about_me = true

    [params.social]
    email = "zenith-john@foxmail.com"
    github = "https://github.com/zenith-john/"
